Local Storage
Hsuwaddyhtat22/To-Do-List-mini-PJ pull request #2
Opened 2023-07-20 08:40 UTC by Hsuwaddyhtat22

Removed all hardcoded items from the tasks array.
Created a new JavaScript file for the new functionality.
Implemented a function for adding a new task (add a new element to the array).
Implemented a procedure for deleting a task (removing a part from the array).
Implemented a process for editing task descriptions.
All changes to the To-Do List are saved in local storage.

2023-07-20 09:44 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Hsuwaddyhtat22 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![TN6](https://user-images.githubusercontent.com/57408419/242633152-ef9bf425-5bec-4c19-bada-7713cd7e55f2.gif)


## To highlight :champagne: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 


## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 09:44 UTC, joel-kalema commented on src/todo.js
> +];
- [ ] Kindly, remove the items from the tasks array  😃

2023-07-20 09:44 UTC, joel-kalema commented on src/todo.js
> +
- [ ] Good job implementing `deleteTask` function, however, when we are deleting `item`, we are not updating our local storage, then when you refresh the page we can be able to see deleted items. In your case, only when the item is completed, the local storage used to be updated but let's do it for both, Kindly, fix it 💪.

![Screenshot 2023-07-20 112043](https://github.com/Hsuwaddyhtat22/To-Do-List-mini-PJ/assets/57408419/2c16b822-d9a7-4968-befb-209928c7bce8)

2023-07-20 09:44 UTC, joel-kalema commented on src/todo.js
> +  const taskText = taskElement.textContent;
- [ ] Also, when we are editing the Task, we are not updating our local storage. Kindly fix it 👍

2023-07-20 11:10 UTC, LionRouge1 requested changes
Hi @Hsuwaddyhtat22, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-20 11:10 UTC, LionRouge1 commented on src/todo.js
> +}
- [ ] As mentioned by the previous reviewer, the localStorage is not update when removing a task which make the task displayed when refresh the page even though it has been removed. Kindly check it to follow the project requirement.
### Take a look at this short video :point_down: to understand more
<video src="https://github.com/Hsuwaddyhtat22/To-Do-List-mini-PJ/assets/91142432/60cc0008-1d55-4570-952d-c0beb4b61096" />

2023-07-21 05:26 UTC, Ibizugbe approved these changes
Hi @Hsuwaddyhtat22 👋🏼👋🏼👋🏼, 

![approved](https://github.com/Hsuwaddyhtat22/To-Do-List-mini-PJ/assets/64643995/a80bb4d4-be8b-48a4-a7bb-f3f6b0231467)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] UI looks great👍🏼.
- [x] When a task is deleted, the changes are saved to local storage👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 05:26 UTC, Ibizugbe commented on src/todo.js
> +  editInput.focus();
[OPTIONAL] Currently, when your tasks are edited, the changes do not get saved in local storage😉. Kindly do well to fix it as this is meant to be a requirement for this milestone and it makes the user experience of the application even better😉.

2023-07-21 08:04 UTC, merged